package internal

import (
	"fmt"
	"slices"
)

// BuiltinTriggers are the dokku triggers every datastore plugin implements
// through a trigger-<name> command of this binary.
//
// install and update are not among them: a plugin's own files for those do
// more than dispatch, so they stay the plugin's to write.
var BuiltinTriggers = []string{
	"post-app-clone-setup",
	"post-app-rename-setup",
	"pre-build",
	"pre-delete",
	"pre-release-builder",
	"pre-restore",
	"pre-start",
	"service-list",
}

// triggerTemplate is the file a plugin ships for a dokku trigger its datastore
// implements.
//
// dokku finds a trigger by looking for a file named after it in the plugin
// directory, so the file exists whatever else happens. Generating it is what
// keeps the work in the definition: this dispatches and does nothing else.
const triggerTemplate = `#!/usr/bin/env bash
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

# generated from the datastore definition. do not edit: it is rewritten by
# make generate.
"${DOKKU_LIB_ROOT}/data/${PLUGIN_COMMAND_PREFIX}/dokku-datastore" trigger %[1]s "$PLUGIN_COMMAND_PREFIX" "$@"
`

// builtinTriggerTemplate is the file a plugin ships for one of the
// BuiltinTriggers. It is generated for the same reason: a trigger this binary
// starts implementing reaches every plugin the next time it is regenerated,
// rather than waiting on a hand-written file in each of them.
const builtinTriggerTemplate = `#!/usr/bin/env bash
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

# generated by dokku-datastore. do not edit: it is rewritten by make generate.
"${DOKKU_LIB_ROOT}/data/${PLUGIN_COMMAND_PREFIX}/dokku-datastore" trigger-%[1]s "$PLUGIN_COMMAND_PREFIX" "$@"
`

// PluginTrigger renders the file a plugin ships for one dokku trigger.
func PluginTrigger(name string) string {
	return fmt.Sprintf(triggerTemplate, name)
}

// PluginBuiltinTrigger renders the file a plugin ships for one of the
// BuiltinTriggers.
func PluginBuiltinTrigger(name string) string {
	return fmt.Sprintf(builtinTriggerTemplate, name)
}

// CheckTriggerNames refuses a trigger a definition declares under the name of
// one of the BuiltinTriggers. Both are written to a file named after the
// trigger, so one would silently replace the other.
func CheckTriggerNames(names []string) error {
	for _, name := range names {
		if slices.Contains(BuiltinTriggers, name) {
			return fmt.Errorf("the %s trigger is implemented by dokku-datastore itself and cannot be declared by a definition", name)
		}
	}

	return nil
}
